---
title: "Statistical Roadmap and Data Intro"
author: "Alan Hubbard"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: refs.bib
---

## Learning Objectives
1. Introduce the data being used in workshp
2. Introduce the statistical roadmap on which the methods are based.

## The Data
The data come from the Effect of water quality, sanitation, hand washing, and
nutritional interventions on child development in rural
Bangladesh (WASH Benefits Bangladesh):
a cluster-randomised controlled trial. The study enrolled enrolled pregnant women in their first or second trimester
from rural villages of Gazipur, Kishoreganj, Mymensingh, and Tangail districts of central Bangladesh, with an average
of eight women per cluster. Groups of eight geographically adjacent clusters were block-randomised, using a random
number generator, into six intervention groups (all of which received weekly visits from a community health promoter
for the first 6 months and every 2 weeks for the next 18 months) and a double-sized control group (no intervention or
health promoter visit). The six intervention groups were: chlorinated drinking water; improved sanitation;
handwashing with soap; combined water, sanitation, and handwashing; improved nutrition through counselling and
provision of lipid-based nutrient supplements; and combined water, sanitation, handwashing, and nutrition. Here,
we report on the prespecified secondary child development outcomes: gross motor milestone achievement assessed
with the WHO module at age 1 year, and communication, gross motor, personal social, and combined scores
measured by the Extended Ages and Stages Questionnaire (EASQ) at age 2 years. Masking of participants was not
possible. Analyses were by intention to treat. This trial is registered with ClinicalTrials.gov, number NCT0
* General purpose framework
* Ecosystem of extension packages for different parameters
* Easy to use for simple cases, customizable

## Motivating Example - Average Treatment Effect (ATE)

##$ Data Structure and Notation

TODO: modify for ATE
Consider $n$ observed units $O_1, \ldots, O_n$, where each random variable $O =
(W, A, Y)$ corresponds to a single observational unit. As discussed before, $W$
are baseline covariates, $A$ is a continuous-valued intervention, and $Y$ an
outcome of interest. We will consider a simple stochastic intervention that
considers counterfactual interventions defined through scalar shifts of the
observed/natural value of the intervention $A$. We'll start by considering a
simple additive shift $d(a,w) = a + \delta$, assuming support a.e. of
$P(A\midW)$. To ease violations of the positivity assumption, we may consider
extensions where $a \leq u(w) - \delta$ or $d(a, w) = a$ if $a \geq u(w) -
\delta$.

##$ Defining the Causal Effect of a Average Treatment Effect


##$ Interpreting the Causal Effect of a Stochastic Intervention

## Estimating an ATE with `tmle3`

* example code here
* how to extract/interpret the results


## `tmle3` Specifications

* wraps up all the details of the estimation strategy into a cohesive spec
* a function to search for these (similar to sl3_list_learners)
* example of applying a different spec

## Customizing `tmle3`

* A new set of parameters (which set)
* How much can we simplify this process

## Using the Delta method

* smooth transform of a parameter (or parameters)
* lay out math here

## Summary

* Do we want a summary section

## Exercises

### Introductory

1. Change the learner list

2. Estimate ATE for another intervention

3. 

4. ...

5. ...

### Intermediate

1. Estimate PAF 

2. Add known likelihood for g


### Advanced

1. ...

2. ...

## References

